name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: perl:latest

    permissions:
      id-token: write
      pages: write

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - run: |
          apt -qqq update
          apt -qqq install nodejs
          cpanm -qn Data::Mirror LWP::Protocol::https HTML5::DOM Image::Size Lingua::EN::Titlecase Template::Liquid

          ./bfgdata.pl

      - uses: actions/configure-pages@v6

      - uses: actions/upload-pages-artifact@v5

      - uses: actions/deploy-pages@v5

